
# FROM python:3.7
# 
# 
# ARG shared_workspace=/opt/workspace
# RUN mkdir -p ${shared_workspace}/data
# 
# ARG 
# WORKDIR /app
# COPY . /app
# EXPOSE 5000
# RUN pip install -r requirements.txt
# ENTRYPOINT ["python"]
# CMD ["app.py"]
# CMD ["server.py"]